config/routes.rb
Rails.application.routes.draw do

  resources :crumbs
  root 'application#index'

  get '/we_will_miss_you', to: 'application#we_will_miss_you'
end

app/models/crumb.rb
class Crumb < ActiveRecord::Base
  validates :label, presence: true
  validates :number, presence: true
  validates :field_key, uniqueness: true, presence: true

  scope :visible, lambda { where(visible: true) }
  scope :nested,  lambda { where("visual_options @> hstore(?, ?)",'has_nested', 'true') }

  def nested_elements
    nested_elements = []
    if self.visual_options && self.visual_options['has_nested'] == "true"
      master_key = self.visual_options['master_key'] ? self.visual_options['master_key'] : self.field_key

      nested_elements = self.class.nested.select{ |crumb| crumb.visual_options.has_key?('master_key') }
    end
    nested_elements
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate

  def index
    @odometer_crumbs = Crumb.visible.select{ |c| (c.visual_options.nil? || c.visual_options["odometer"]!= 'false') }.select{|c| c.visual_options.nil? || !c.visual_options.has_key?('master_key') }
    @text_crumbs     = Crumb.visible.select{ |c| (c.visual_options && c.visual_options["odometer"] == 'false') }
  end

  def we_will_miss_you

  end

  protected

  def authenticate
    if  Rails.env.production?
      authenticate_or_request_with_http_basic do |username, password|
        username == Sloth::Application.config.http_auth.name && password == Sloth::Application.config.http_auth.password
      end
    end
  end
end

app/controllers/crumbs_controller.rb
class CrumbsController < ApplicationController
  before_action :set_crumb, only: [:show, :edit, :update, :destroy]

  # GET /crumbs
  def index
    @crumbs = Crumb.all
  end

  # GET /crumbs/1
  def show
  end

  # GET /crumbs/new
  def new
    @crumb = Crumb.new
  end

  # GET /crumbs/1/edit
  def edit
  end

  # POST /crumbs
  def create
    @crumb = Crumb.new(crumb_params)

    if @crumb.save
      redirect_to @crumb, notice: 'Crumb was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /crumbs/1
  def update
    if @crumb.update(crumb_params)
      redirect_to @crumb, notice: 'Crumb was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /crumbs/1
  def destroy
    @crumb.destroy
    redirect_to crumbs_url, notice: 'Crumb was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crumb
      @crumb = Crumb.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def crumb_params
      params.require(:crumb).permit(:number, :field_key, :label, :visible, :visual_options)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crumbs_helper.rb
module CrumbsHelper
end

app/views/application/index.html.haml
.row
  .col-sm-12.col-md-4
    .main_image_conteiner
      = image_tag 'empire_strikes_eck.jpg'

    / %ul.slothy
    /   - (1..12).each do |i|
    /     %li= I18n.t("sloth.img_line#{i}").html_safe

  .col-sm-12.col-md-8
    #crumbs_container
      %ul.nav.nav-tabs
        %li.active
          %a{ href: '#home', 'data-toggle' => "tab" }= 'Home'
        - (@odometer_crumbs + @text_crumbs).each_with_index do |crumb_data, index|
          %li
            - data = crumb_data.nested_elements.any? ? crumb_data.nested_elements.map(&:field_key).join(',') : crumb_data.field_key
            %a{ href: "##{crumb_data.field_key}", 'data-toggle' => "tab", 'data-field-key' => data, onclick: "tabClickInit(this);" }= index+1
        %li
          %a{ href: '#bought_stuff', 'data-toggle' => "tab" }= '100200'
        %li
          %a{ href: '#faked_users', 'data-toggle' => "tab" }= '100300'
        %li
          %a{ href: '#faked_personalities', 'data-toggle' => "tab" }= '100400'
        %li
          %a{ href: '#drama_btn', 'data-toggle' => "tab" }= '100500'


      .tab-content
        #home{ class: 'active tab-pane fade in'}
          .home_tab
            #roller.textroller

        - @odometer_crumbs.each do |crumb_data|
          %div{ id: crumb_data.field_key, class: 'tab-pane fade' }
            - if crumb_data.nested_elements.any? # build nested elements on the same tab
              - crumb_data.nested_elements.each do |nested_crumb|
                .number_description
                  = nested_crumb.label
                - # odometer
                .odometer.odometer-theme-car{ class: nested_crumb.field_key, data: { theme: "car", number: nested_crumb.number } }
            - else
              .number_description
                = crumb_data.label
              - # odometer
              .odometer.odometer-theme-car{ class: crumb_data.field_key, data: { theme: "car", number: crumb_data.number } }

        - # tab w/o odometer
        - @text_crumbs.each do |text_crumb_data|
          %div{ id: text_crumb_data.field_key, class: 'tab-pane fade' }
            .number_description
              = text_crumb_data.label

        #bought_stuff{ class: 'tab-pane fade' }
          %h4= "Bought items on Makerist"
          .images_conteiner
            = image_tag "pattern_1.jpg", class: 'normal_image'
            = image_tag "pattern_2.jpg", class: 'normal_image'

        #faked_users{ class: 'tab-pane fade' }
          %h4= "Faked User Accounts on Makerist"
          .images_conteiner
            %ul{style: 'list-style: none;'}
              - ['Florian Eck', 'Harry Hirsch', 'Hokus Pokus', 'Chuck Testa', 'Gooby Plz'].each do |fake|
                %li= fake

        #faked_personalities{ class: 'tab-pane fade' }
          %h4= "Faked Personalities"
          .images_conteiner
            = image_tag "flo_1.jpg", class: 'normal_image'
            = image_tag "flo_2.jpg", class: 'normal_image'

        #drama_btn{ class: 'tab-pane fade' }
          %div.with-top-small-margin
            = image_tag 'unicorn.gif', class: 'unicorn_image'
            = link_to(image_tag('push-to-add-drama.png', class: 'drama_button'), we_will_miss_you_path)



/`/"==..__"=..__ _    _..-==/"/"_
/           .-,`/"=/ /\ \""/_)==/"/"``
/          ( (    | | | \/ |
/           \ '.  |  \;  \ /
/            |  \ |   |   ||
/       ,-._.'  |_|   |   ||
/      .\_/\     -'   ;   Y
/     |  `  |        /    |-.
/     '. __/_    _.-'     /'
/            `'-.._____.-' "
/

app/views/application/we_will_miss_you.html.haml
.will_miss_you_container
  .row
    %h3= "We will miss you 'cause you are the one who..."
    .col-sm-12.col-md-12
      %div{ id: "carousel-example-generic", class: "carousel slide", 'data-ride' => "carousel", 'data-interval' => '3000' }

        - # Wrapper for slides
        %div{ class: "carousel-inner" }
          - %w(connect math fix hack install code users bugs).each_with_index do |image_prefix, index|
            %div.item{ class: index ==0 ? "active" : '' }
              = image_tag "#{image_prefix}_things.jpg", class: 'carousel_image'

        - # Indicators
        %ol.carousel-indicators
          %li{ class: "active", 'data-target' => "#carousel-example-generic", 'data-slide-to' => "0" }
          %li{ 'data-target' => "#carousel-example-generic", 'data-slide-to' => "1" }
          %li{ 'data-target' => "#carousel-example-generic", 'data-slide-to' => "2" }
          %li{ 'data-target' => "#carousel-example-generic", 'data-slide-to' => "3" }
          %li{ 'data-target' => "#carousel-example-generic", 'data-slide-to' => "4" }
          %li{ 'data-target' => "#carousel-example-generic", 'data-slide-to' => "5" }
          %li{ 'data-target' => "#carousel-example-generic", 'data-slide-to' => "6" }
          %li{ 'data-target' => "#carousel-example-generic", 'data-slide-to' => "7" }

  .clearfix
  .row.with-top-margin
    .col-sm-12.col-md-4
      %h4= 'Add more drama...'
      = link_to '#', { 'data-toggle' => "modal", 'data-target' => "#moreDrama" } do
        = image_tag('push-to-add-drama.png', class: 'drama_button')

      %div{ class: "modal fade", id: "moreDrama", tabindex: "-1", role: "dialog", 'aria-labelledby' => "myModalLabel", 'aria-hidden' => "true" }
        %div{ class: "modal-dialog", role: "document" }
          .modal-content
            .modal-body
              %div{ style: 'text-align:center;'}
                %h4= "We won't forget your:"
                = image_tag "dont_care.jpg", class: 'drama_container'

    .col-sm-12.col-md-4
      %h4= '...add even more drama...'
      = link_to '#', { 'data-toggle' => "modal", 'data-target' => "#evenMoreDrama" } do
        = image_tag('push-to-add-drama.png', class: 'drama_button')

      %div{ class: "modal fade", id: "evenMoreDrama", tabindex: "-1", role: "dialog", 'aria-labelledby' => "myModalLabel", 'aria-hidden' => "true" }
        %div{ class: "modal-dialog", role: "document" }
          .modal-content
            .modal-body
              %div{ style: 'text-align:center;'}
                = image_tag "sad_unicorn.gif", class: 'drama_unicorn'

    .col-sm-12.col-md-4
      %h4= '...even more drama?..'
      = link_to '#', { 'data-toggle' => "modal", 'data-target' => "#noDrama" } do
        = image_tag('push-to-add-drama.png', class: 'drama_button')

      %div{ class: "modal fade", id: "noDrama", tabindex: "-1", role: "dialog", 'aria-labelledby' => "myModalLabel", 'aria-hidden' => "true" }
        %div{ class: "modal-dialog", role: "document" }
          .modal-content
            .modal-body
              %div{ style: 'text-align:center;'}
                %blockquote
                  %p= "Everything will be okay in the end. If it's not okay, it's not the end."
                  %footer= 'John Lennon'
                = image_tag "sid_ok.jpg"
              %h3= "So see you at makerist parties!"
              %div.with-top-margin{ style: 'text-align:center;'}
                = image_tag "party_things.gif"
:javascript
  window.img_url = "#{ asset_path('butterfly.gif') }";

  function JSFX_StartEffects(){
    JSFX.MakeSpring (10, "<img src="+ window.img_url +">");
  }

app/views/crumbs/_form.html.haml
= form_for @crumb do |f|
  - if @crumb.errors.any?
    #error_explanation
      %h2= "#{pluralize(@crumb.errors.count, "error")} prohibited this crumb from being saved:"
      %ul
        - @crumb.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :number
    = f.number_field :number
  .field
    = f.label :field_key
    = f.text_field :field_key
  .field
    = f.label :label
    = f.text_area :label
  .field
    = f.label :visual_options
    = f.text_area :visual_options
  .field
    = f.label :visible
    = f.check_box :visible
  .actions
    = f.submit 'Save'

app/views/crumbs/edit.html.haml
%h1 Editing crumb

= render 'form'

= link_to 'Show', @crumb
\|
= link_to 'Back', crumbs_path

app/views/crumbs/index.html.haml
%h1 Listing crumbs

%table
  %thead
    %tr
      %th Number
      %th Field Key
      %th Label
      %th Visible
      %th
      %th
      %th

  %tbody
    - @crumbs.each do |crumb|
      %tr
        %td= crumb.number
        %td= crumb.field_key
        %td= crumb.label
        %td= crumb.visible
        %td= link_to 'Show', crumb
        %td= link_to 'Edit', edit_crumb_path(crumb)
        %td= link_to 'Destroy', crumb, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Crumb', new_crumb_path

app/views/crumbs/new.html.haml
%h1 New crumb

= render 'form'

= link_to 'Back', crumbs_path

app/views/crumbs/show.html.haml
%p#notice= notice

%p
  %b Number:
  = @crumb.number
%p
  %b Field Key:
  = @crumb.field_key
%p
  %b Label:
  = @crumb.label
%p
  %b Visible:
  = @crumb.visible
%p
  %b Visual Options:
  = @crumb.visual_options.inspect


= link_to 'Edit', edit_crumb_path(@crumb)
\|
= link_to 'Back', crumbs_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}
    %meta{content: "", name: "description"}
    %meta{content: "", name: "author"}
    %title Starter Template for Bootstrap

    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if lt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js"

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-inverse.navbar-fixed-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{type: "button", data: {toggle: "collapse", target: "#navbar"}, aria: {expanded: "false", controls: "navbar"} }
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "Flocke", root_path, class: "navbar-brand"
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              = link_to 'Crumbs', crumbs_path

    .container
      - flash.each do |name, msg|
        = content_tag :div, class: "alert alert-#{name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do
          %button.close{type: "button", data: {dismiss: "alert"} }
            %span{aria: {hidden: "true"} } &times;
            %span.sr-only Close
          = msg
      = yield